### ISSUE TITLE
Glyph Editor: "Lock aspect ratio" is not respected in bulk-edit for paths

### ISSUE THREAD

**Issue by ThePaSch** [glyphr-studio/Glyphr-Studio-2#154]
**Describe the bug & what the expected behavior should be:**
When attempting to bulk-edit paths for a given glyph, the "Lock aspect ratio" option is not respected. When said option is ticked, manually adjusting the height or width should proportionally adjust the other respective value; however, this is currently not the case.

**Steps to reproduce the bug:**

1. Create a new project.
2. Create a new glyph for any character.
3. Add a new path for said glyph; add any number of points, then apply.
4. Deselect that path.
5. Tick the "lock aspect ratio" box in the attribute editor's "Bulk-edit paths" section.
6. Adjust either width or height in that section.
7. The other respective value is not adjusted accordingly.

**Comment by mattlag** [comment]
Thank you for filing the bug! I was able to reproduce it. 

One note is that the on-canvas handle adjustments *do* honor the locked aspect ratio... but not the width/height inputs.

**Comment by mattlag** [comment]
I'm still looking into this one... it seems like it only happens sometimes, but sometimes it works as expected.  There is also another hard to reproduce bug with the Number Input control while using the keyboard arrow keys to increment/decrement... It seems to multiply instead of just increment.

Anyway, I tried to include this in 2.0.1, but it's a bit more complex than I thought.

**Comment by mattlag** [comment]
Fixed in v2.1.1
